# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#
Rails.application.routes.draw do
  get '/', to: 'index#index'
  # get '/maps', to: 'maps#show'
  get '/editor', to: 'map_editor#show'
  get '/holdings/:bibId', to: 'holdings#show'
  post '/maps/uploadRefImg', to: 'maps#upload_ref'

  def add_swagger_route(http_method, path, opts = {})
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/v2/floors', controller_name: 'floors', action_name: 'index'
  add_swagger_route 'DELETE', '/v2/floors/{id}', controller_name: 'floors', action_name: 'destroy'
  add_swagger_route 'GET', '/v2/floors/{id}', controller_name: 'floors', action_name: 'show'
  add_swagger_route 'POST', '/v2/floors', controller_name: 'floors', action_name: 'create'
  add_swagger_route 'PUT', '/v2/floors', controller_name: 'floors', action_name: 'floors_put'
  add_swagger_route 'GET', '/v2/libraries', controller_name: 'libraries', action_name: 'index'
  add_swagger_route 'DELETE', '/v2/libraries/{id}', controller_name: 'libraries', action_name: 'destroy'
  add_swagger_route 'POST', '/v2/libraries', controller_name: 'libraries', action_name: 'create'
  add_swagger_route 'PUT', '/v2/libraries', controller_name: 'libraries', action_name: 'libraries_put'
  add_swagger_route 'GET', '/v2/rules', controller_name: 'rules', action_name: 'index'
  add_swagger_route 'DELETE', '/v2/rules/{id}', controller_name: 'rules', action_name: 'destroy'
  add_swagger_route 'POST', '/v2/rules', controller_name: 'rules', action_name: 'create'
  add_swagger_route 'GET', '/v2/search', controller_name: 'search', action_name: 'index'
  add_swagger_route 'GET', '/v2/stacks', controller_name: 'stacks', action_name: 'index'
  add_swagger_route 'DELETE', '/v2/stacks/{id}', controller_name: 'stacks', action_name: 'destroy'
  add_swagger_route 'GET', '/v2/stacks/{id}', controller_name: 'stacks', action_name: 'show'
  add_swagger_route 'POST', '/v2/stacks', controller_name: 'stacks', action_name: 'create'
  add_swagger_route 'PUT', '/v2/stacks', controller_name: 'stacks', action_name: 'stacks_put'
end
