#
# db/schema.rb
#
# DB schema for API
#
# Stub generated by Swagger-codegen
#
# Copyright (c) 2017 Ke Qian
#

ActiveRecord::Schema.define(version: 1) do

  create_table "errors", id: false, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.integer "code"
    t.string "message"
    t.string "fields"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "floors", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string "name"
    t.integer "size_x"
    t.integer "size_y"
    t.text "geojson"
    t.text "map"
    t.string "ref"
    t.bigint "library"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["library", "name"], name: "index_floors_on_library_and_name"
  end

  create_table "libraries", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string "name"
    t.string "latitude"
    t.string "longitude"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "rules", primary_key: "rule_id", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string "rule_type"
    t.string "call_number"
    t.string "rule"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "stacks", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.integer "cx"
    t.integer "cy"
    t.integer "lx"
    t.integer "ly"
    t.integer "rotation"
    t.string "start_class"
    t.integer "start_subclass"
    t.string "start_subclass2"
    t.string "end_class"
    t.integer "end_subclass"
    t.string "end_subclass2"
    t.integer "oversize"
    t.bigint "floor"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["floor"], name: "fk_rails_7e8ff62bb5"
  end

  add_foreign_key "floors", "libraries", column: "library"
  add_foreign_key "stacks", "floors", column: "floor"
end
