#
# app/controllers/application_controller.rb
#
# Stub generated by Swagger-codegen
#
# Copyright (c) 2017 Ke Qian
#

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
