#
# app/controllers/libraries_controller.rb
#
# API controller to handle libraries
#
# Stub generated by Swagger-codegen
#
# Copyright (c) 2017 Ke Qian
#

class LibrariesController < ApplicationController
  def index
    ret = []
    Library.all.each do |library|
      ret << {
        id: library.id,
        name: library.name,
        latitude: library.latitude,
        longitude: library.longitude
      }
    end
    render json: ret
  end

  def destroy
    Library.find(params[:id]).destroy
    render json: 'OK'.to_json
  end

  def create
    library = Library.new
    library.name = params[:name]
    library.latitude = params[:latitude]
    library.longitude = params[:longitude]
    if library.save
      render json: library.id.to_json
    else
      render json: {error: 'bad request', code: 400, message: 'unable to create record'}, status: 400
    end
  end

  def libraries_put
    library = Library.find(params[:id])
    library.name = params[:name] || library.name
    library.latitude = params[:latitude] || library.latitude
    library.longitude = params[:longitude] || library.longitude
    if library.save
      render json: 'OK'.to_json
    else
      render json: {error: 'bad request', code: 400, message: 'unable to update record'}, status: 400
    end
  end
end
