#
# app/controllers/rules_controller.rb
#
# API controller to handle rules
#
# Stub generated by Swagger-codegen
#
# Copyright (c) 2017 Ke Qian
#

class RulesController < ApplicationController
  def index
    ret = []
    Rule.find_each do |rule|
      ret << {
        rule_type: rule.rule_type,
        rule_id: rule.rule_id,
        call_number: rule.call_number,
        rule: rule.rule
      }
    end
    render json: ret
  end

  def destroy
    Rule.find(params[:id]).destroy
    render json: 'OK'.to_json
  end

  def create
    rule = Rule.new
    rule.rule_type = params[:rule_type]
    rule.rule_id = params[:rule_id]
    rule.call_number = params[:call_number]
    rule.rule = params[:rule]
    if rule.save
      render json: rule.id.to_json
    else
      render json: {error: 'bad request', code: 400, message: 'unable to create record'}, status: 400
    end
  end
end
