# waffles-muggles
#
# CS 5150 Navigation in Library Stacks.
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

class Floor < ApplicationRecord
  has_many :stacks
  validates :name, presence: true, uniqueness: { scope: :library, message: 'has already been taken by the library' }, length: { in: 1..255 }
  validates :size_x, allow_nil: true, numericality: { only_integer: true, greater_than: 0 }
  validates :size_y, allow_nil: true, numericality: { only_integer: true, greater_than: 0 }
  validates :geojson, allow_nil: true, length: { minimum: 1 }
  validates :map, allow_nil: true, length: { minimum: 1 }
  validates :ref, allow_nil: true, length: { in: 1..255 }
end
